main:
  push:
    - docker:
        image: node:20
        volumes:
          - /root/.npm:cow
      stages:
        - name: 安装依赖并构建
          script: npm install && npm run build
        - name: 列出构建产物
          script: ls dist/
